name: Descarga periodica de datos

on:
  workflow_dispatch:
  schedule:
    - cron: '30 * * * *'

jobs:
  fetch_data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Descarga de datos
        run: ./scripts/download_data.sh
      - name: Procesar datos
        run: python3 ./scripts/parse_data.py
      - name: Guardar cambios
        uses: EndBug/add-and-commit@v7 # You can change this to use a specific version
        with:
          # The arguments for the `git add` command (see the paragraph below for more info)
          # Default: '.'
          add: 'datos'

          # The name of the user that will be displayed as the author of the commit
          # Default: author of the commit that triggered the run
          author_name: Covid-bot

          # The email of the user that will be displayed as the author of the commit
          # Default: author of the commit that triggered the run
          author_email: covid-bot@example.com

          # The message for the commit
          # Default: 'Commit from GitHub Actions (name of the workflow)'
          message: 'Datos actualizados'
